version: '3.8'

services:
  list-task-service:
    build: ./list-task-service
    ports:
      - "5001:5001"

  update-task-service:
    build: ./update-task-service
    ports:
      - "5002:5002"

  delete-task-service:
    build: ./delete-task-service
    ports:
      - "5003:5003"